# 学习导读：cclaw/profiles/posix-cli.cmake
# 所属层次：构建 profile。
# 阅读重点：这里为不同目标选择平台和功能开关，阅读时重点看 CMake 变量如何裁剪源码。
# 注释说明：如果注释与代码冲突，以代码行为和测试为准。
set(CC_PROFILE_TARGET_PLATFORM posix)

# POSIX CLI 是功能最全的桌面学习 profile：文件、HTTP、记忆、shell、插件和多 LLM 后端全部打开。
set(CC_PROFILE_ENABLE_FILE_TOOLS ON)
set(CC_PROFILE_ENABLE_HTTP_TOOL ON)
set(CC_PROFILE_ENABLE_MEMORY ON)
set(CC_PROFILE_ENABLE_CLI ON)
set(CC_PROFILE_ENABLE_SHELL ON)
set(CC_PROFILE_ENABLE_PLUGIN ON)
set(CC_PROFILE_ENABLE_DOCKER_SANDBOX ON)
set(CC_PROFILE_ENABLE_SQLITE ON)
set(CC_PROFILE_ENABLE_OPENAI ON)
set(CC_PROFILE_ENABLE_OLLAMA ON)
set(CC_PROFILE_ENABLE_ANTHROPIC ON)

# 默认路径指向应用目录中的 config/plugins/soul/user，运行时数据放在 build 树下。
if(CC_PROFILE_APPLICATION_DIR)
    set(CC_PROFILE_DEFAULT_CONFIG_PATH "${CMAKE_SOURCE_DIR}/${CC_PROFILE_APPLICATION_DIR}/config/config.json")
    set(CC_PROFILE_DEFAULT_PLUGIN_CONFIG_PATH "${CMAKE_SOURCE_DIR}/${CC_PROFILE_APPLICATION_DIR}/config/plugins.json")
    set(CC_PROFILE_DEFAULT_DATA_DIR "${CMAKE_BINARY_DIR}/${CC_PROFILE_APPLICATION_DIR}/runtime/data")
    set(CC_PROFILE_DEFAULT_WORKSPACE_PATH "${CMAKE_BINARY_DIR}/${CC_PROFILE_APPLICATION_DIR}/runtime/workspace")
    set(CC_PROFILE_DEFAULT_MEMORY_PATH "${CMAKE_BINARY_DIR}/${CC_PROFILE_APPLICATION_DIR}/runtime/data/memory.json")
    set(CC_PROFILE_DEFAULT_SOUL_FILE "${CMAKE_SOURCE_DIR}/${CC_PROFILE_APPLICATION_DIR}/config/soul.md")
    set(CC_PROFILE_DEFAULT_USER_FILE "${CMAKE_SOURCE_DIR}/${CC_PROFILE_APPLICATION_DIR}/config/user.md")
endif()
