# 学习导读：cclaw/profiles/windows-cli.cmake
# 所属层次：构建 profile。
# 阅读重点：这里为不同目标选择平台和功能开关，阅读时重点看 CMake 变量如何裁剪源码。
# 注释说明：如果注释与代码冲突，以代码行为和测试为准。
set(CC_PROFILE_TARGET_PLATFORM windows)

# Windows CLI 尽量对齐 POSIX CLI，但 Docker sandbox 默认关闭，进程/路径能力走 Windows platform。
set(CC_PROFILE_ENABLE_FILE_TOOLS ON)
set(CC_PROFILE_ENABLE_HTTP_TOOL ON)
set(CC_PROFILE_ENABLE_MEMORY ON)
set(CC_PROFILE_ENABLE_CLI ON)
set(CC_PROFILE_ENABLE_SHELL ON)
set(CC_PROFILE_ENABLE_PLUGIN ON)
set(CC_PROFILE_ENABLE_MULTI_AGENT ON)
set(CC_PROFILE_ENABLE_RUN_QUEUE ON)
set(CC_PROFILE_ENABLE_TOOL_POOL ON)
set(CC_PROFILE_ENABLE_SKILLS ON)
set(CC_PROFILE_ENABLE_SKILL_WATCHER ON)
set(CC_PROFILE_ENABLE_PLUGIN_HOT_RELOAD ON)
set(CC_PROFILE_ENABLE_PLUGIN_WORKERS ON)
set(CC_PROFILE_ENABLE_MCP ON)
set(CC_PROFILE_ENABLE_MCP_STDIO ON)
set(CC_PROFILE_ENABLE_MCP_HTTP ON)
set(CC_PROFILE_ENABLE_SUBAGENTS ON)
set(CC_PROFILE_ENABLE_ACTIVE_MEMORY ON)
set(CC_PROFILE_ENABLE_DOCKER_SANDBOX OFF)
set(CC_PROFILE_ENABLE_SQLITE ON)
set(CC_PROFILE_ENABLE_OPENAI ON)
set(CC_PROFILE_ENABLE_OLLAMA ON)
set(CC_PROFILE_ENABLE_ANTHROPIC ON)

# 默认路径仍指向应用目录，运行时数据输出到当前 app build 根的 runtime。
if(CC_PROFILE_APPLICATION_DIR)
    set(CC_PROFILE_DEFAULT_CONFIG_PATH "${CMAKE_SOURCE_DIR}/${CC_PROFILE_APPLICATION_DIR}/config/config.json")
    set(CC_PROFILE_DEFAULT_DATA_DIR "${CMAKE_BINARY_DIR}/runtime/data")
    set(CC_PROFILE_DEFAULT_WORKSPACE_PATH "${CMAKE_BINARY_DIR}/runtime/workspace")
    set(CC_PROFILE_DEFAULT_MEMORY_PATH "${CMAKE_BINARY_DIR}/runtime/data/memory.json")
    set(CC_PROFILE_DEFAULT_SOUL_FILE "${CMAKE_SOURCE_DIR}/${CC_PROFILE_APPLICATION_DIR}/config/soul.md")
    set(CC_PROFILE_DEFAULT_USER_FILE "${CMAKE_SOURCE_DIR}/${CC_PROFILE_APPLICATION_DIR}/config/user.md")
endif()
